#version 450
#extension GL_ARB_separate_shader_objects : enable

#define WORKGROUP_SIZE 16

layout(local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE) in;

layout(push_constant) uniform PushUniforms
{
    vec2 eyePoint;
} pushConst;

layout(binding = 0, r8ui) uniform uimage2D targetImage;

void main() {
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
	imageStore(targetImage, uv, uvec4(2,0,0,0));
}